<template>
  <block-pages
    :description="description[$route.params.id]"
    :title="title[$route.params.id]"
  ></block-pages>
</template>

<script>
export default {
  data() {
    return {
      title: {
        0: 'Türkmen döwlet ykdysadyýet we dolandyryş institutynyň ilkinji Partiýa guramasy',
        1: 'Türkmen döwlet ykdysadyýet we dolandyryş institutynyň Kärdeşler arkalaşygynyň ilkinji guramasy',
        2: 'Türkmen döwlet ykdysadyýet we dolandyryş institutynyň ilkinji Ýaşlar guramasy',
        3: 'Türkmen döwlet ykdysadyýet we dolandyryş institutynyň Ilkinji Zenanlar guramasy',
      },
      description: {
        0: '<p>Türkmen döwlet ykdysadyýet we dolandyryş institutynyň ilkinji Partiýa guramasy özüniň ähli işini Gahryman Arkadagymyzyň «Döwlet adam üçindir!» hem-de Arkadagly Serdarymyzyň «Watan diňe halky bilen Watandyr!, Döwlet diňe halky bilen döwletdir!» diýen parasatly şygarynyň esasynda alyp barýar we Garaşsyz döwletimiziň özygtyýarlylygyny, hemişelik Bitaraplygyny pugtalandyrmaga, jemgyýetiň kämilligini gazanmaga ýardam bermäge gönükdirýär.</p><p>Berkarar döwletiň täze eýýamynyň Galkynyşy döwründe hormatly Prezidentimiz Serdar Berdimuhamedowyň beýik maksatly tutumly işlerini ýaşlaryň arasynda wagyz-nesihat etmekde Türkmen döwlet ykdysadyýet we dolandyryş institutynda Türkmenistanyň Demokratik partiýasynyň ilkinji partiýa guramasy netijeli işleri alyp barýar.</p><p>Türkmenistanyň Demokratik partiýasynyň ilkinji partiýa guramalarynyň wezipeleri esasan hem şulardan ybarat bolup durýar:</p><ul><li><p>partiýanyň Maksatnamasyny durmuşa geçirmekden we Tertipnamasynyň talaplaryny berjaý etmek üçin zerur çäreleri görmekden;</p></li><li><p>özüniň içeri partiýa işleri bilen baglanyşykly kararlary özbaşdak kabul etmekden hem ýerine ýetirmekden, syýasy we durmuş-ykdysady meseleler boýunça peýdaly täzelikleriň, göreldeli başlangyçlaryň öňbaşçysy bolup çykyş etmekden;</p></li><li><p>ýokarky partiýa guramalarynyň kararlaryny taýýarlamakdan, ara alyp maslahatlaşmakdan we amala aşyrmaga işeňňir gatnaşmakdan;</p></li><li><p>partiýa agzalygyna kabul etmekden we zerur bolan ýagdaýda agzalykdan çykarmakdan, partiýa agzalarynyň hasabyny ýöretmekden;</p></li><li><p>agzalyk töleglerini ýygnamakdan, toplanan serişdäni ýokarky partiýa komitetiniň hasaplaşyk hasabyna geçirmekden;</p></li><li><p>ählihalk we ýerli saýlawlary, sala salşyklary taýýarlamakdan hem-de geçirmäge işeňňir gatnaşmakdan;</p></li><li><p>saýlawly döwlet edaralaryna, ýokarky partiýa guramalarynyň saýlawly edaralaryna, beýleki saýlawly wezipelere dalaşgärleri hödürlemekden, olaryň saýlanmagyna ýardam bermekden, şonuň ýaly hem, şol guramalardan yzyna çagyrmak barada teklipleri bermekden.</p></li></ul><p>Bulardan başga-da ýaşlary şu günüň talabyna laýyk terbiýelemek, olary halkymyza, Watanymyza, Hormatly Prezidentimize wepaly edip ýetişdirmek ilkinji Partiýa guramasynyň esasy wezipeleriniň biri bolup durýar.</p>',
        1: '<p>Institutyň Kärdeşler arkalaşygynyň ilkinji guramasynyň wezipesi öz agzalarynyň zähmet, durmuş-ykdysady hukuklaryny we bähbitlerini aýan etmek, durmuşa geçirmek hem-de goramak bolup durýar. Şulardan ugur alyp, Türkmen döwlet ykdysadyýet we dolandyryş institutynyň Kärdeşler arkalaşygynyň ilkinji guramasy institutda mugallymlaryň, talyplaryň we beýleki işgärleriň iş hem-de ýaşaýyş şertlerini gowulandyrmak, nilli däpleri dowam etdirýän nesli terbiýelemek, oňat şertlerde dynç almaklaryny üpjün etmek, zähmetde öňdebaryjylara mynasyp baha berip, olaryň çekýän yhlasly zähmetini höweslendirmek ýaly mynasyp işleri alyp barýar. Bu gurama öz gurluşyny özbaşdak işläp taýýarlaýar we tassyklaýar, şeýle hem işiniň ugurlaryny kesgitleýär, gurultaýlary, konferensiýalary, ýygnaklary geçirýär. Şeýle-de Kärdeşler arkalaşyklary öz agzalarynyň arasynda we umumy ýaşaýyş jaýlarynda ýaşaýan talyplar bilen duşuşyklary geçirýär hem-de olaryň ýaşaýyş şertleri bilen yzygiderli tanşyp durýar.</p>',
        2: '<p>Türkmen döwlet ykdysadyýet we dolandyryş institutynyň ilkinji Ýaşlar guramasy ýaşlary watansöýüjilik, halallyk ruhunda terbiýelemek, olaryň giň dünýägaraýyşly, ylymly-bilimli, sagdyn bedenli, ruhy taýdan arassa, kämil ýaşlar bolup ýetişmekleri ugrunda giň gerimli maksatnamalaýyn işleri alyp barýar. Institutyň ilkinji Ýaşlar guramasy maksatnamalaýyn işlerini Türkmenistanda ýaşlar baradaky döwlet syýasatynyň 2021-2025-nji ýyllar üçin döwlet Maksatnamasyna, şeýle hem Türkmenistanyň Bilim ministrliginiň, Türkmenistanyň Magtymguly adyndaky Ýaşlar Guramasynyň hem-de institutyň ýaşlar syýasaty boýunça ýerine ýetirmeli çäreleriniň meýilnamalaryna laýyklykda alyp barýar. Institutyň ilkinji Ýaşlar guramasy ýurdumyzda geçirilýän bäsleşiklere ýaşlarymyzyň yzygiderli we işjeň gatnaşmaklaryna ýardam edýär. Has takygy, Türkmenistanyň ýaşlarynyň arasynda geçirilýän Ýaş alymlaryň bäsleşigine, Türkmenistanyň Ýaşlar baýragynyň eýesi diýen ady almak ugrundaky bäsleşige, şeýle hem ýaşlaryň ukyp -başarnyklaryny açyp görkezýän döredijilik bäsleşiklerine, ýagny talyp gyzlaryň arasynda Talyp gözeli, talyp oglanlaryň arasynda Gerçek ýigit ýaly bäsleşiklere hem-de Talyp joşguny festiwalyna ýaşlary işjeň gatnaşdyrmak boýunça işleri alyp barýar.</p>',
        3: '<p>Ilkinji Zenanlar guramalary jemgyýetçilik guramalarynyň biri bolmak bilen ýurdumyzyň zenan raýatlarynyň isleglerine hem-de bäbitleriniň umumylygyna esaslanyp, Türkmenistanyň kanunlaryna we öz Tertipnamasyna laýyklykda özygtyýarlyklarynyň çäklerinde wekilçilik etmek bilen, döwleti dolandyryş işlerinde, ykdysadyýetde, ylymda, bilimde, lukmançylykda, aragatnaşyk, hyzmat ediş we medeni gumanitar ulgamlarda uly işleri bitirýärler.</p><p>Döwletimiziň milli kanunçylygynda aýallaryň hukuklarynyň aýratyn orna eýedigininiň we gender deňligini durmuşa geçirmegiň kanuny esaslary goýuldy. Şeýle bolansoň, institutyň professor-mugallymlarynyň we talyplarynyň arasynda wagyz-nesihat maslahatlary yzygiderli geçirilýär. Türkmenistanyň Haly muzeýinde, Türkmenistanyň Döwlet medeniýet merkeziniň Döwlet Muzeýinde we Türkmenistanyň şekillendiriş sungaty muzeýinde geçirilýän sergilere talyplar bilen gezelençler guralýar. Institutyň talyp gyz-gelinleriniň arasynda edep-terbiýe, saglyk we arassaçylyk bilen bagly, jemgyýetde özüňi alyp barmagyň kadalary barada söhbetdeşlikler we maslahatlar, il arasynda hormatlanýan enelerimiz bilen duşuşyklar geçirilýär.</p><p><em>Meýilnama boýunça geçrilýän işler:</em></p><p>«<em>Milli mirasymyza sylagym-sarpam, Arkadagly Serdarymyz-howandar arkam</em>» atly wagyz-nesihat maslahaty;</p><p>«<em>Talyp gözeli-2022</em>» atly Türkmenistanyň ähli ýokary okuw jaýlarynyň talyp gyzlarynyň arasynda geçirilýän bäsleşik;</p><p>«<em>Öý-ojagyň gelşigi maşgala mukaddesligi</em>» atly talyp gyzlaryň arsynda tertip-düzgün we arassaçylyk barada halypa zenanlar bilen duşuşyklar;</p><p>«<em>El hünäri- il gezer</em>» atly çäre;</p><p>«<em>Sagdyn bedende-sagdyn ruh</em>» atly institutyň talyp gyzlarynyň arasynda sport çäreleri;</p><p>Talyplar saglyk öýüniň lukmanlary bilen «<em>Arassaçylyk saglygyň girewidir</em>» atly wagyz-nesihat duşuşygy;</p><p>«<em>Türkmen halysy-ynsan gözelliginiň nepis nusgasy</em>» atly ussat halyçylar we döredijilik işgärleri bilen duşuşyklar;</p><p>«<em>Ömrümiň örki çaga</em>» ady bilen institutyň aýal-gyzlarynyň arasynda söhbetdeşlikler;</p><p>«<em>Bilimler we talyp ýaşlar güni</em>» mynasybetli instituta täze kabul edilen 1-nji ýyl talyplar bilen geçirilýän aýdym-sazly dabaraly çäre.</p>',
      },
    }
  },
}
</script>

<style lang="scss" scoped></style>
